# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
    - refs/tags/v*
    - dev
pr:
- master


pool:
  name: Hosted VS2017

steps:

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './'
  displayName: 'install npm submodules'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      npm run windows_x64
      rm lib/*.ilk
      rm lib/*.pdb
      ls lib
  displayName: 'clean windows_x64'

- task: ArchiveFiles@2
  displayName: 'Archive lib'
  inputs:
    rootFolderOrFile: lib
    includeRootFolder: false
    archiveType: tar
    archiveFile: 'pcan.tar.gz'

- task: cURLUploader@2
  displayName: 'Upload pcan.passoa'
  inputs:
    files: 'pcan.tar.gz'
    serviceEndpoint: 'csding.net'
    remotePath: 'repertory/cxb/pcan.tar.gz?version=$(Build.SourceBranchName)-windows-x64'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: './'
    customCommand: 'run build'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  
- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: './'
    customRegistry: 'useFeed'
    publishEndpoint: 'npmjs.org'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))