# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
    - refs/tags/v*
    - dev
pr:
- master


pool:
  name: Hosted VS2017

steps:

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './'
  displayName: 'install npm submodules'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      npm run windows_x64
      rm build/*.ilk
      rm build/*.pdb
      ls build
  displayName: 'clean windows_x64'

- task: ArchiveFiles@2
  displayName: 'Archive build'
  inputs:
    rootFolderOrFile: build
    includeRootFolder: true
    archiveType: tar
    archiveFile: '$(Build.ArtifactStagingDirectory)/pcan.tar.gz'

- task: GitHubRelease@0
  displayName: "GitHub release (create)"
  inputs:
    gitHubConnection: "ga-connect"
    addChangeLog: false
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: './'
    customCommand: 'run build'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  
- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: './'
    customRegistry: 'useFeed'
    publishEndpoint: 'npmjs.org'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))

- script: |
    echo %CVIPUSER%
    curl -u %CVIPUSER%:%CVIPPASS% -H "Accept: application/json" -H "Content-type: application/json" -X POST -d "{'action': 'published'}" https://passoa.coding.net/api/cci/job/244432/trigger
  displayName: 'Command Line Script'
  env:
    CVIPUSER: ptos650d93zh
    CVIPPASS: 09760a524a3a1acf77cd85a953202d2f15383ffd
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))