# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
    - refs/tags/v*
    - dev
pr:
- master


pool:
  name: Hosted VS2017

steps:

- script: |
    npm install
  displayName: 'install npm submodules'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      npm run windows_x86
      rm dist/*.ilk
      mv dist/pcan.pdb binary/pcan.pdb
      ls dist
  displayName: 'build windows_x86'

- task: cURLUploader@2
  displayName: 'Upload pdb'
  inputs:
    files: 'binary/pcan.pdb'
    serviceEndpoint: 'csding.net'
    remotePath: 'repertory/cxb/pcan.pdb?version=$(Build.SourceBranchName)-windows-x86'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))

- task: ArchiveFiles@2
  displayName: 'Archive dist'
  inputs:
    rootFolderOrFile: dist
    includeRootFolder: false
    archiveType: tar
    archiveFile: 'pcan.tar.gz'

- task: cURLUploader@2
  displayName: 'Upload pcan.passoa'
  inputs:
    files: 'pcan.tar.gz'
    serviceEndpoint: 'csding.net'
    remotePath: 'repertory/cxb/pcan.tar.gz?version=$(Build.SourceBranchName)-windows-x86'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: './'
    customCommand: 'run build'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  
- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: './'
    customRegistry: 'useFeed'
    publishEndpoint: 'npmjs.org'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))